// Credits:
// LucasDower

export const ja_JP = {
    display_name: '日本語',
    language_code: 'ja-JP',
    translations: {
        something_went_wrong: '予期せぬ問題が発生しました。',
        description: '3Dモデルを .schematic .litematic .schem .nbt などのMinecraftの形式に変換するツールです。',
        init: {
            initialising: '初期化中...',
            ready: '準備が完了しました',
        },
        settings: {
            heading: '設定',
            components: {
                language: '言語',
                overrideHeight: '高さの上書き',
            },
            changing_language: '言語を変更中...',
            changed_language: '言語を変更しました',
        },
        import: {
            heading: '1. インポート',
            button: 'メッシュの読み込み',
            importing_mesh: 'メッシュをインポート中...',
            imported_mesh: 'メッシュをインポートしました',
            rendering_mesh: 'メッシュをレンダリング中...',
            rendered_mesh: 'メッシュをレンダリングしました',
            no_vertices_loaded: '頂点を読み込めませんでした',
            no_triangles_loaded: '三角形を読み込めませんでした',
            could_not_scale_mesh: 'メッシュを正しくスケールできませんでした - メッシュは2Dである可能性があります。高さが 0 以外になるように回転してください。',
            invalid_encoding: '認識できない文字が見つかりました。UTF-8を使用してエンコードしてください。',
            invalid_face_data: '面データに予期しない数の頂点データがあります。: {{count, number}}',
            too_many_triangles: 'インポートされたメッシュには {{count, number}} 個の三角形があります。',
            vertex_triangle_count: '{{vertex_count, number}} vertices, {{triangle_count, number}} Blender などの DDC で単純化することを検討してください。',
            missing_normals: '一部の頂点には法線が定義されていないため、ボクセルが正しく位置合わせされない可能性があります。',
            failed_to_parse_line: '「{{error}}」のため、「{{line}}」の解析に失敗しました。',
            gltf_experimental: 'GLTF インポーターは実験的なものであるため、予期しない結果が生じる可能性があります。',
            unsupported_image_type: '「{{file_name}}」を読み取れません。サポートされていないファイル形式「{{file_type}}」です。',
            components: {
                input: '3Dモデル (.obj, .glb)',
                no_file_chosen: 'ファイルが選択されていません',
                rotation: '回転',
            },
        },
        materials: {
            heading: '2. マテリアル',
            button: 'マテリアルを更新',
            updating_materials: 'マテリアルを更新中...',
            updated_materials: 'マテリアルを更新しました',
            components: {
                'no_materials_loaded': 'マテリアルが読み込まれていません',
                'material_type': 'タイプ',
                'solid': 'ソリッド',
                'textured': 'テクスチャ',
                'no_image_loaded': '画像が選択されていません',
                'choose': '画像を選択',
                'texture_filtering': 'フィルター',
                'texture_wrap': 'ラップ',
                'transparency': '透過',
                'diffuse_map': 'マップ',
                'alpha': 'アルファ',
                'alpha_map': 'アルファマップ',
                'alpha_channel': 'アルファチャンネル',
                'linear': '補完',
                'nearest': '近接',
                'clamp': '範囲制限',
                'repeat': '繰り返し',
                'none': 'なし',
                'alpha_constant': 'アルファ値を指定',
                'diffuse_map_alpha_channel': 'マップのアルファチャンネル',
            },
        },
        voxelise: {
            heading: '3. ボクセル化',
            button: 'メッシュをボクセル化',
            loading_voxel_mesh: 'ボクセルメッシュを読み込み中...',
            loaded_voxel_mesh: 'ボクセルメッシュを読み込みました',
            rendering_voxel_mesh: 'ボクセルメッシュをレンダリング中...',
            rendered_voxel_mesh: 'ボクセルメッシュをレンダリングしました',
            voxel_count: 'ボクセル数 {{count, number}}',
            voxel_mesh_dimensions: '大きさ {{x, number}} x {{y, number}} x {{z, number}}',
            components: {
                constraint_axis: '軸の制限',
                size: 'サイズ',
                algorithm: 'アルゴリズム',
                ambient_occlusion: '周囲を閉鎖',
                multisampling: 'マルチサンプリング',
                voxel_overlap: 'ボクセルの重なり',
                colour: '色',
                x_axis: 'X (幅) (赤)',
                y_axis: 'Y (高さ) (緑)',
                z_axis: 'Z (奥行き) (青)',
                ray_based: 'Ray-based',
                bvh_ray: 'BVH Ray-based',
                ncrb: 'NCRB',
                average_recommended: '平均 (推奨)',
                first: '最初',
                on_recommended: 'オン (推奨)',
                off_faster: 'オフ (速さ優先)',
            },
        },
        assign: {
            heading: '3. 割り当て',
            button: 'ブロックの割り当て',
            loading_block_mesh: 'ブロックメッシュを読み込み中...',
            loaded_block_mesh: 'ブロックメッシュを読み込みました',
            rendering_block_mesh: 'ブロックメッシュをレンダリング中...',
            rendered_block_mesh: 'ブロックメッシュをレンダリングしました',
            deselected_blocks: '選択を解除したブロック {{count, number}} 個',
            selected_blocks: '選択中のブロック {{count, number}} 個',
            found_blocks: '見つかったブロック {{count, number}} 個',
            block_not_namespaced: '"{{block_name}}" is not namespaced correctly, do you mean "minecraft:{{block_name}}"?',
            could_not_use_block: 'Could not use "{{block_name}}" as it is unsupported',
            reading_palette: 'レンダリング {{file_name}}...',
            block_palette_missing_light_blocks: 'Block palette contains no light blocks to place',
            blocks_missing_textures: '{{count, number}} palette block(s) are missing atlas textures, they will not be used',
            falling_blocks: '{{count, number}} blocks will fall due to gravity when this structure is placed',
            components: {
                texture_atlas: 'テクスチャアトラス',
                block_palette: '使用するブロック',
                dithering: 'ディザリング',
                dithering_magnitude: 'ディザリングの大きさ',
                fallable_blocks: '落下するブロック',
                colour_accuracy: '色の正確さ',
                smart_averaging: 'スマートな平均化',
                smoothness: '滑らかさ',
                calculate_lighting: 'ライティングの計算',
                light_threshold: 'ライトのしきい値',
                vanilla: 'バニラ',
                ordered: 'オーダー',
                random: 'ランダム',
                off: 'オフ',
                replace_falling: '落下するブロックを落下しないブロックに置き換える',
                replace_fallable: '落下する部分だけ落下しないブロックに置き換える',
                do_nothing: '何もしない',
                search: '検索...',
            },
        },
        export: {
            heading: '5. エクスポート',
            button: 'ストラクチャーにエクスポート',
            exporting_structure: 'ストラクチャーにエクスポート中...',
            exported_structure: 'ストラクチャーにエクスポートしました',
            schematic_unsupported_blocks: '{{count, number}} blocks ({{unique, number}} unique) are not supported by the .schematic format, Stone blocks will used instead. Try using the schematic-friendly palette, or export using .litematica',
            nbt_exporter_too_big: 'Structure blocks only support structures of size 48x48x48, blocks outside this range will be removed',
            components: {
                exporter: 'エクスポートする',
                litematic: 'Litematic (.litematic)',
                schematic: 'Schematic (.schematic)',
                sponge_schematic: 'Sponge Schematic (.schem)',
                structure_blocks: 'ストラクチャーブロック (.nbt)',
                indexed_json: 'インデックス付き JSON (.json)',
                uncompressed_json: '非圧縮 JSON (.json)',
            },
        },
        misc: {
            red: 'レッド',
            green: 'グリーン',
            blue: 'ブルー',
            alpha: 'アルファ',
            on: 'オン',
            off: 'オフ',
            advanced_settings: '高度な設定'
        },
        toolbar: {
            view_mesh: 'メッシュを表示する',
            view_voxel_mesh: 'ボクセルメッシュを表示する',
            view_block_mesh: 'ブロックメッシュを表示する',
            toggle_grid: 'グリッドの切り替え',
            toggle_axes: '軸の切り替え',
            toggle_night_vision: '暗視に切り替える',
            toggle_slice_viewer: 'スライスビューアの切り替え',
            decrement_slice: 'スライスをデクリメントします',
            increment_slice: 'スライスを増やす',
            zoom_in: 'ズームイン',
            zoom_out: 'ズームアウト',
            reset_camera: 'カメラをリセット',
            perspective_camera: '透視投影カメラ',
            orthographic_camera: '平行投影カメラ',
            open_github_repo: 'GitHub のリポジトリを開く',
            open_github_issues: 'GitHub の issues を開く',
            join_discord: 'Discordサーバーに参加する',
        }
    },
};
